<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>netstandard2.1</TargetFramework>
    <OutputType>Library</OutputType>
    <LangVersion>latest</LangVersion>
    <AssemblyName>RoboPatch</AssemblyName>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="RoboPatch.API/**/*.cs" />
    <Compile Remove="GameCode/**/*.cs" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="RoboPatch.API\RoboPatch.API.csproj" />
  </ItemGroup>

  <ItemGroup>
    <!-- Core Unity DLLs -->
    <Reference Include="Managed/UnityEngine">
      <HintPath>Managed/UnityEngine.dll</HintPath>
    </Reference>
    <Reference Include="Managed/UnityEngine.CoreModule">
      <HintPath>Managed/UnityEngine.CoreModule.dll</HintPath>
    </Reference>
    <Reference Include="Managed/UnityEngine.AssetBundleModule">
      <HintPath>Managed/UnityEngine.AssetBundleModule.dll</HintPath>
    </Reference>
    <Reference Include="Managed/UnityEngine.InputLegacyModule">
      <HintPath>Managed/UnityEngine.InputLegacyModule.dll</HintPath>
    </Reference>
    <Reference Include="Managed/UnityEngine.JSONSerializeModule">
      <HintPath>Managed/UnityEngine.JSONSerializeModule.dll</HintPath>
    </Reference>

    <!-- Canvas stuff -->
    <Reference Include="Managed/UnityEngine.UI">
      <HintPath>Managed/UnityEngine.UI.dll</HintPath>
    </Reference>
    <Reference Include="Managed/UnityEngine.UIModule">
      <HintPath>Managed/UnityEngine.UIModule.dll</HintPath>
    </Reference>
    <Reference Include="Managed/UnityEngine.TextRenderingModule">
      <HintPath>Managed/UnityEngine.TextRenderingModule.dll</HintPath>
    </Reference>

    <!-- BepInEx -->
    <Reference Include="BepInEx.Core">
      <HintPath>Managed/BepInEx.Core.dll</HintPath>
    </Reference>
    <Reference Include="BepInEx.Unity.Mono">
      <HintPath>Managed/BepInEx.Unity.Mono.dll</HintPath>
    </Reference>
    <Reference Include="0Harmony">
      <HintPath>Managed/0Harmony.dll</HintPath>
    </Reference>
  </ItemGroup>

</Project>
